version: '3.7'

services:
  todo-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    tty: true
    container_name: todo-webapp
    command: air
    volumes:
      - .:/app:rw
      - ~/go/pkg:/go/pkg
    ports:
      - 8989:8989
    depends_on:
      todo-webapp-postgres:
        condition: service_healthy
    env_file:
      - local.env

  todo-webapp-postgres:
    image: postgres:12.2
    container_name: todo-webapp-postgres
    restart: always
    security_opt:
      - "seccomp:unconfined"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - local.env
